controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

activity:
    path: /api/activity/{id}
    controller: App\Controller\ActivityController::showActivity
    methods: GET
activities:
    path: /api/activities
    controller: App\Controller\ActivityController::getActivities
    methods: GET
new_activity:
    path: /api/activity/new
    controller: App\Controller\ActivityController::newActivity
    methods: POST
get_user_profile:
    path: /api/userprofile
    controller: App\Controller\UserProfileController::getUserProfileInfos
    methods: GET
set_user_profile:
    path: /api/userprofile
    controller: App\Controller\UserProfileController::setUserProfileInfos
    methods: POST
get_profile_picture:
    path: /api/profilepicture
    controller: App\Controller\UserProfileController::getUserProfilePicture
    methods: GET
set_profile_picture:
    path: /api/profilepicture
    controller: App\Controller\UserProfileController::setUserProfilePicture
    methods: POST
api_login_check:
    path: /api/login_check
api_logout:
    path: /api/logout
app_home:
    path: /api/
test_app:
    path: /test
    controller: App\Controller\TestController::printTest
    methods: GET